/*
 * yaml_graph.c
 *
 * Parser for the restricted graph description format generated by NanoGraph.
 * Supports flattened subgraph name mangling, graph-level platform metadata,
 * manifest-driven named node parameters, current IO fields and current arc
 * attributes. C90/C89 source; no heap allocation.
 */

#define _CRT_SECURE_NO_WARNINGS
#include "yaml_graph.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>

typedef enum
{
    YG_SECTION_NONE,
    YG_SECTION_NODES,
    YG_SECTION_ARCS,
    YG_SECTION_FORMATS
} YG_Section;

static const char *yg_skip_space(const char *p)
{
    while ((*p == ' ') || (*p == '\t')) ++p;
    return p;
}

static int yg_indent(const char *p)
{
    int n;
    n = 0;
    while (*p != '\0')
    {
        if (*p == ' ') n += 1;
        else if (*p == '\t') n += 4;
        else break;
        ++p;
    }
    return n;
}

static void yg_remove_eol(char *s)
{
    int n;
    n = (int)strlen(s);
    while (n > 0)
    {
        if ((s[n - 1] == '\n') || (s[n - 1] == '\r'))
        {
            s[n - 1] = '\0';
            --n;
        }
        else break;
    }
}

static void yg_copy_trimmed(char *dst, int dst_size, const char *src)
{
    const char *begin;
    const char *end;
    int n;
    if (dst_size <= 0) return;
    begin = yg_skip_space(src);
    end = begin + strlen(begin);
    while ((end > begin) && ((end[-1] == ' ') || (end[-1] == '\t'))) --end;
    n = (int)(end - begin);
    if (n >= dst_size) n = dst_size - 1;
    if (n > 0) memcpy(dst, begin, (size_t)n);
    dst[n] = '\0';
}

static void yg_copy_text_value(char *dst, int dst_size, const char *src)
{
    char temp[YG_MAX_LINE];
    int n;
    char quote;
    int copy_n;
    yg_copy_trimmed(temp, (int)sizeof(temp), src);
    n = (int)strlen(temp);
    if (n >= 2)
    {
        quote = temp[0];
        if (((quote == '\'') || (quote == '"')) && (temp[n - 1] == quote))
        {
            copy_n = n - 2;
            if (copy_n >= dst_size) copy_n = dst_size - 1;
            if (copy_n > 0) memcpy(dst, temp + 1, (size_t)copy_n);
            if (dst_size > 0) dst[copy_n] = '\0';
            return;
        }
    }
    yg_copy_trimmed(dst, dst_size, temp);
}

static int yg_key_value(const char *line, char *key, int key_size, const char **value)
{
    const char *p;
    const char *colon;
    int n;
    p = yg_skip_space(line);
    colon = strchr(p, ':');
    if (colon == NULL) return 0;
    n = (int)(colon - p);
    while ((n > 0) && ((p[n - 1] == ' ') || (p[n - 1] == '\t'))) --n;
    if (n >= key_size) n = key_size - 1;
    if (n > 0) memcpy(key, p, (size_t)n);
    key[n] = '\0';
    *value = yg_skip_space(colon + 1);
    return 1;
}

static int yg_parse_int(const char *text, int *value)
{
    const char *p;
    char *end;
    long v;
    p = yg_skip_space(text);
    if (*p == '\0') return 0;
    v = strtol(p, &end, 10);
    if (end == p) return 0;
    end = (char *)yg_skip_space(end);
    if (*end != '\0') return 0;
    if ((v > (long)INT_MAX) || (v < (long)INT_MIN)) return 0;
    *value = (int)v;
    return 1;
}

static int yg_parse_double(const char *text, double *value)
{
    const char *p;
    char *end;
    double v;
    p = yg_skip_space(text);
    if (*p == '\0') return 0;
    v = strtod(p, &end);
    if (end == p) return 0;
    end = (char *)yg_skip_space(end);
    if (*end != '\0') return 0;
    *value = v;
    return 1;
}

static int yg_parse_params(const char *text, double *values, int max_values, int *count)
{
    const char *p;
    char *end;
    int n;
    double v;
    p = text;
    n = 0;
    for (;;)
    {
        p = yg_skip_space(p);
        if (*p == '\0') break;
        v = strtod(p, &end);
        if (end == p) return 0;
        if (n >= max_values) return 0;
        values[n++] = v;
        p = end;
    }
    *count = n;
    return 1;
}

int yg_split_instance_name(const char *name, char *base_name, int base_name_size, int *instance_index)
{
    int len;
    int i;
    int digits_begin;
    long value;
    if ((name == NULL) || (base_name == NULL) || (base_name_size <= 0) || (instance_index == NULL)) return 0;
    len = (int)strlen(name);
    i = len - 1;
    while ((i >= 0) && isdigit((unsigned char)name[i])) --i;
    digits_begin = i + 1;
    if ((digits_begin >= len) || (i < 0) || (name[i] != '_'))
    {
        yg_copy_trimmed(base_name, base_name_size, name);
        *instance_index = -1;
        return 0;
    }
    value = strtol(name + digits_begin, NULL, 10);
    if (value > (long)INT_MAX)
    {
        yg_copy_trimmed(base_name, base_name_size, name);
        *instance_index = -1;
        return 0;
    }
    if (i >= base_name_size) i = base_name_size - 1;
    if (i > 0) memcpy(base_name, name, (size_t)i);
    base_name[i] = '\0';
    *instance_index = (int)value;
    return 1;
}

int yg_split_io_name(const char *name,
                     char *base_name,
                     int base_name_size,
                     int *instance_index)
{
    int len;
    int close_pos;
    int open_pos;
    int i;
    long value;
    char number[32];
    int number_len;

    if ((name == NULL) || (base_name == NULL) ||
        (base_name_size <= 0) || (instance_index == NULL)) return 0;

    len = (int)strlen(name);
    close_pos = len - 1;
    if ((close_pos < 2) || (name[close_pos] != ']'))
    {
        yg_copy_trimmed(base_name, base_name_size, name);
        *instance_index = -1;
        return 0;
    }

    open_pos = close_pos - 1;
    while ((open_pos >= 0) && isdigit((unsigned char)name[open_pos])) --open_pos;
    if ((open_pos < 0) || (name[open_pos] != '[') || (open_pos == close_pos - 1))
    {
        yg_copy_trimmed(base_name, base_name_size, name);
        *instance_index = -1;
        return 0;
    }

    number_len = close_pos - open_pos - 1;
    if (number_len >= (int)sizeof(number)) return 0;
    for (i = 0; i < number_len; ++i) number[i] = name[open_pos + 1 + i];
    number[number_len] = '\0';
    value = strtol(number, NULL, 10);
    if (value > (long)INT_MAX) return 0;

    i = open_pos;
    if (i >= base_name_size) i = base_name_size - 1;
    if (i > 0) memcpy(base_name, name, (size_t)i);
    base_name[i] = '\0';
    *instance_index = (int)value;
    return 1;
}

int yg_split_mangled_name(const char *name,
                          char *scope, int scope_size,
                          char *local_name, int local_name_size,
                          char *base_name, int base_name_size,
                          int *instance_index, int *hierarchy_depth)
{
    const char *p;
    const char *last;
    int depth;
    int n;
    if ((name == NULL) || (scope == NULL) || (local_name == NULL) ||
        (base_name == NULL) || (instance_index == NULL) || (hierarchy_depth == NULL) ||
        (scope_size <= 0) || (local_name_size <= 0) || (base_name_size <= 0)) return 0;

    last = NULL;
    depth = 0;
    p = name;
    while ((p = strstr(p, "__")) != NULL)
    {
        last = p;
        ++depth;
        p += 2;
    }
    if (last != NULL)
    {
        n = (int)(last - name);
        if (n >= scope_size) n = scope_size - 1;
        if (n > 0) memcpy(scope, name, (size_t)n);
        scope[n] = '\0';
        yg_copy_trimmed(local_name, local_name_size, last + 2);
    }
    else
    {
        scope[0] = '\0';
        yg_copy_trimmed(local_name, local_name_size, name);
    }
    *hierarchy_depth = depth;
    yg_split_instance_name(local_name, base_name, base_name_size, instance_index);
    return 1;
}

static void yg_init_node(YG_Node *node)
{
    memset(node, 0, sizeof(*node));
    node->instance_index = -1;
}

static void yg_init_endpoint(YG_Endpoint *ep)
{
    memset(ep, 0, sizeof(*ep));
    ep->port = -1;
    ep->instance_index = -1;
}

static void yg_init_arc(YG_Arc *arc)
{
    memset(arc, 0, sizeof(*arc));
    yg_init_endpoint(&arc->source);
    yg_init_endpoint(&arc->destination);
}

static void yg_init_format(YG_Format *format)
{
    memset(format, 0, sizeof(*format));
    format->format_id = -1;
}

static void yg_set_error(YG_Graph *graph, int line_no, const char *text)
{
    graph->error_line = line_no;
    yg_copy_trimmed(graph->error_text, (int)sizeof(graph->error_text), text);
}

static void yg_fill_name_parts(YG_ItemKind kind,
                               const char *name, char *scope, int scope_size,
                               char *local_name, int local_size,
                               char *base_name, int base_size,
                               int *instance_index, int *depth)
{
    const char *p;
    const char *last;
    int n;
    int d;

    last = NULL;
    d = 0;
    p = name;
    while ((p = strstr(p, "__")) != NULL)
    {
        last = p;
        ++d;
        p += 2;
    }
    if (last != NULL)
    {
        n = (int)(last - name);
        if (n >= scope_size) n = scope_size - 1;
        if (n > 0) memcpy(scope, name, (size_t)n);
        scope[n] = '\0';
        yg_copy_trimmed(local_name, local_size, last + 2);
    }
    else
    {
        scope[0] = '\0';
        yg_copy_trimmed(local_name, local_size, name);
    }
    *depth = d;

    if (kind == YG_ITEM_IO)
        yg_split_io_name(local_name, base_name, base_size, instance_index);
    else
        yg_split_instance_name(local_name, base_name, base_size, instance_index);
}

static int yg_start_node(YG_Node *node, const char *line)
{
    const char *p;
    p = yg_skip_space(line);
    if (*p != '-') return 0;
    ++p;
    p = yg_skip_space(p);
    yg_init_node(node);
    if (strncmp(p, "IO:", 3) == 0)
    {
        node->kind = YG_ITEM_IO;
        yg_copy_text_value(node->name, (int)sizeof(node->name), p + 3);
    }
    else if (strncmp(p, "node:", 5) == 0)
    {
        node->kind = YG_ITEM_NODE;
        yg_copy_text_value(node->name, (int)sizeof(node->name), p + 5);
    }
    else return 0;
    yg_fill_name_parts(node->kind, node->name,
                       node->scope, (int)sizeof(node->scope),
                       node->local_name, (int)sizeof(node->local_name),
                       node->base_name, (int)sizeof(node->base_name),
                       &node->instance_index, &node->hierarchy_depth);
    return 1;
}

static int yg_parse_node_property(YG_Node *node, const char *line)
{
    char key[64];
    const char *value;
    if (!yg_key_value(line, key, (int)sizeof(key), &value)) return 0;
#define YG_INT_FIELD(k,field,flag) if (strcmp(key,k)==0) { if(!yg_parse_int(value,&node->field)) return 0; node->present|=flag; return 1; }
#define YG_DBL_FIELD(k,field,flag) if (strcmp(key,k)==0) { if(!yg_parse_double(value,&node->field)) return 0; node->present|=flag; return 1; }
    YG_INT_FIELD("framel",framel,YG_NODE_HAS_FRAMEL)
    YG_DBL_FIELD("period",period,YG_NODE_HAS_PERIOD)
    YG_DBL_FIELD("per_hr",per_hr,YG_NODE_HAS_PER_HR)
    YG_DBL_FIELD("per_day",per_day,YG_NODE_HAS_PER_DAY)
    if (strcmp(key,"domain") == 0) { yg_copy_text_value(node->domain,(int)sizeof(node->domain),value); node->present|=YG_NODE_HAS_DOMAIN; return 1; }
    YG_INT_FIELD("nbchan",nbchan,YG_NODE_HAS_NBCHAN)
    YG_DBL_FIELD("samprt",samprt,YG_NODE_HAS_SAMPRT)
    YG_DBL_FIELD("samprt_percent_accuracy",samprt_percent_accuracy,YG_NODE_HAS_SAMPRT_ACCURACY)
    if (strcmp(key,"unit") == 0) { yg_copy_text_value(node->unit,(int)sizeof(node->unit),value); node->present|=YG_NODE_HAS_UNIT; return 1; }
    YG_DBL_FIELD("scale",scale,YG_NODE_HAS_SCALE)
    if (strcmp(key,"data_type") == 0) { yg_copy_text_value(node->data_type,(int)sizeof(node->data_type),value); node->present|=YG_NODE_HAS_DATA_TYPE; return 1; }
    if (strcmp(key,"time_stamp") == 0) { yg_copy_text_value(node->time_stamp,(int)sizeof(node->time_stamp),value); node->present|=YG_NODE_HAS_TIME_STAMP; return 1; }
    if (strcmp(key,"interleaving") == 0) { yg_copy_text_value(node->interleaving,(int)sizeof(node->interleaving),value); node->present|=YG_NODE_HAS_INTERLEAVING; return 1; }
    if (strcmp(key,"params") == 0)
    {
        if (!yg_parse_params(value,node->params,YG_MAX_PARAMS,&node->nb_params)) return 0;
        node->present |= YG_NODE_HAS_PARAMS;
        return 1;
    }
    if (strcmp(key,"paramFile") == 0) { yg_copy_text_value(node->param_file,(int)sizeof(node->param_file),value); node->present|=YG_NODE_HAS_PARAM_FILE; return 1; }
    if (strcmp(key,"paramtxt") == 0) { yg_copy_text_value(node->paramtxt,(int)sizeof(node->paramtxt),value); node->present|=YG_NODE_HAS_PARAMTXT; return 1; }
    YG_INT_FIELD("preset",preset,YG_NODE_HAS_PRESET)
    YG_INT_FIELD("minopp",minopp,YG_NODE_HAS_MINOPP)
    if (strcmp(key,"script") == 0) { yg_copy_text_value(node->script,(int)sizeof(node->script),value); node->present|=YG_NODE_HAS_SCRIPT; return 1; }
    if (strcmp(key,"formatID") == 0) { yg_copy_text_value(node->format_id,(int)sizeof(node->format_id),value); node->present|=YG_NODE_HAS_FORMAT_ID; return 1; }
#undef YG_INT_FIELD
#undef YG_DBL_FIELD
    /* "parameters:" itself and future fields are accepted. */
    return 1;
}

static int yg_add_named_parameter(YG_Node *node, const char *line)
{
    char key[YG_MAX_PARAM_NAME];
    const char *value;
    YG_NamedParameter *p;
    if (!yg_key_value(line,key,(int)sizeof(key),&value)) return 0;
    if (node->nb_named_parameters >= YG_MAX_NAMED_PARAMS) return -1;
    p = &node->named_parameter[node->nb_named_parameters++];
    memset(p,0,sizeof(*p));
    yg_copy_trimmed(p->name,(int)sizeof(p->name),key);
    yg_copy_text_value(p->value,(int)sizeof(p->value),value);
    node->present |= YG_NODE_HAS_NAMED_PARAMETERS;
    return 1;
}

static int yg_parse_endpoint(const char *line, const char *prefix, YG_Endpoint *ep)
{
    const char *p;
    const char *q;
    char *end;
    long port;
    p = yg_skip_space(line);
    if (strncmp(p,prefix,strlen(prefix)) != 0) return 0;
    p += strlen(prefix);
    port = strtol(p,&end,10);
    if ((end == p) || (port < 0) || (port > (long)INT_MAX)) return 0;
    q = yg_skip_space(end);
    if (strncmp(q,"IO:",3) == 0) { ep->kind=YG_ITEM_IO; q+=3; }
    else if (strncmp(q,"node:",5) == 0) { ep->kind=YG_ITEM_NODE; q+=5; }
    else return 0;
    ep->port = (int)port;
    yg_copy_text_value(ep->name,(int)sizeof(ep->name),q);
    yg_fill_name_parts(ep->kind, ep->name,
                       ep->scope,(int)sizeof(ep->scope),
                       ep->local_name,(int)sizeof(ep->local_name),
                       ep->base_name,(int)sizeof(ep->base_name),
                       &ep->instance_index,&ep->hierarchy_depth);
    return 1;
}

static int yg_start_arc(YG_Arc *arc, const char *line)
{
    const char *p;
    p=yg_skip_space(line);
    if (*p!='-') return 0;
    ++p;
    p=yg_skip_space(p);
    yg_init_arc(arc);
    return yg_parse_endpoint(p,"OPort_",&arc->source);
}

static int yg_parse_arc_property(YG_Arc *arc, const char *line)
{
    char key[64];
    const char *value;
    if (yg_parse_endpoint(line,"IPort_",&arc->destination)) return 1;
    if (!yg_key_value(line,key,(int)sizeof(key),&value)) return 0;
    if (strcmp(key,"arc_name") == 0) { yg_copy_text_value(arc->arc_name,(int)sizeof(arc->arc_name),value); arc->present|=YG_ARC_HAS_NAME; }
    else if (strcmp(key,"buffer_size") == 0) { if(!yg_parse_int(value,&arc->buffer_size)) return 0; arc->present|=YG_ARC_HAS_BUFFER_SIZE; }
    else if (strcmp(key,"data_type") == 0) { yg_copy_text_value(arc->data_type,(int)sizeof(arc->data_type),value); arc->present|=YG_ARC_HAS_DATA_TYPE; }
    else if (strcmp(key,"sample_rate") == 0) { if(!yg_parse_double(value,&arc->sample_rate)) return 0; arc->present|=YG_ARC_HAS_SAMPLE_RATE; }
    else if (strcmp(key,"nb_channels") == 0) { if(!yg_parse_int(value,&arc->nb_channels)) return 0; arc->present|=YG_ARC_HAS_NB_CHANNELS; }
    else if (strcmp(key,"interleaving") == 0) { yg_copy_text_value(arc->interleaving,(int)sizeof(arc->interleaving),value); arc->present|=YG_ARC_HAS_INTERLEAVING; }
    else if (strcmp(key,"refresh") == 0) { yg_copy_text_value(arc->refresh,(int)sizeof(arc->refresh),value); arc->present|=YG_ARC_HAS_REFRESH; }
    else if (strcmp(key,"jitter_percent") == 0) { if(!yg_parse_double(value,&arc->jitter_percent)) return 0; arc->present|=YG_ARC_HAS_JITTER; }
    else if (strcmp(key,"overlay_with") == 0) { yg_copy_text_value(arc->overlay_with,(int)sizeof(arc->overlay_with),value); arc->present|=YG_ARC_HAS_OVERLAY_WITH; }
    else if (strcmp(key,"formatID") == 0) { yg_copy_text_value(arc->format_id,(int)sizeof(arc->format_id),value); arc->present|=YG_ARC_HAS_FORMAT_ID; }
    else if (strcmp(key,"script") == 0) { yg_copy_text_value(arc->script,(int)sizeof(arc->script),value); arc->present|=YG_ARC_HAS_SCRIPT; }
    return 1;
}

int yg_read_file(const char *filename, YG_Graph *graph)
{
    FILE *f;
    char line[YG_MAX_LINE];
    YG_Section section;
    YG_Node *current_node;
    YG_Arc *current_arc;
    YG_Format *current_format;
    char current_format_field[32];
    const char *p;
    const char *value;
    char key[64];
    int line_no;
    int n;
    int ind;
    int in_named_parameters;
    int rc;

    if ((filename == NULL) || (graph == NULL)) return YG_ERR_SYNTAX;
    memset(graph,0,sizeof(*graph));
    f=fopen(filename,"r");
    if (f==NULL) { yg_set_error(graph,0,"cannot open input file"); return YG_ERR_OPEN; }
    section=YG_SECTION_NONE;
    current_node=NULL;
    current_arc=NULL;
    current_format=NULL;
    current_format_field[0]='\0';
    line_no=0;
    in_named_parameters=0;

    while (fgets(line,(int)sizeof(line),f)!=NULL)
    {
        ++line_no;
        n=(int)strlen(line);
        if ((n==(int)sizeof(line)-1) && (line[n-1]!='\n') && !feof(f))
        { yg_set_error(graph,line_no,"input line too long"); fclose(f); return YG_ERR_LINE_TOO_LONG; }
        yg_remove_eol(line);
        ind=yg_indent(line);
        p=yg_skip_space(line);
        if ((*p=='\0') || (*p=='#')) continue;

        if ((ind==0) && yg_key_value(p,key,(int)sizeof(key),&value) && (strcmp(key,"platform")==0))
        {
            yg_copy_text_value(graph->platform,(int)sizeof(graph->platform),value);
            graph->present |= YG_GRAPH_HAS_PLATFORM;
            continue;
        }
        if ((ind==0) && (strcmp(p,"nodes:")==0))
        { section=YG_SECTION_NODES; current_node=NULL; current_arc=NULL; current_format=NULL; in_named_parameters=0; continue; }
        if ((ind==0) && (strcmp(p,"arcs:")==0))
        { section=YG_SECTION_ARCS; current_node=NULL; current_arc=NULL; current_format=NULL; in_named_parameters=0; continue; }
        if ((ind==0) && (strcmp(p,"formats:")==0))
        { section=YG_SECTION_FORMATS; current_node=NULL; current_arc=NULL; current_format=NULL; current_format_field[0]='\0'; in_named_parameters=0; continue; }

        if (section==YG_SECTION_NODES)
        {
            if (*p=='-')
            {
                if (graph->nb_nodes>=YG_MAX_NODES) { yg_set_error(graph,line_no,"too many nodes"); fclose(f); return YG_ERR_TOO_MANY_NODES; }
                current_node=&graph->nodes[graph->nb_nodes];
                if (!yg_start_node(current_node,p)) { yg_set_error(graph,line_no,"invalid node declaration"); fclose(f); return YG_ERR_SYNTAX; }
                ++graph->nb_nodes;
                in_named_parameters=0;
            }
            else
            {
                if (current_node==NULL) { yg_set_error(graph,line_no,"node property before node declaration"); fclose(f); return YG_ERR_SYNTAX; }
                if ((ind>=6) && in_named_parameters)
                {
                    rc=yg_add_named_parameter(current_node,p);
                    if (rc<0) { yg_set_error(graph,line_no,"too many named node parameters"); fclose(f); return YG_ERR_TOO_MANY_PARAMS; }
                    if (rc==0) { yg_set_error(graph,line_no,"invalid named node parameter"); fclose(f); return YG_ERR_SYNTAX; }
                }
                else
                {
                    in_named_parameters=0;
                    if (yg_key_value(p,key,(int)sizeof(key),&value) && (strcmp(key,"parameters")==0) && (*value=='\0'))
                    { in_named_parameters=1; current_node->present|=YG_NODE_HAS_NAMED_PARAMETERS; }
                    else if (!yg_parse_node_property(current_node,p))
                    { yg_set_error(graph,line_no,"invalid node property"); fclose(f); return YG_ERR_SYNTAX; }
                }
            }
        }
        else if (section==YG_SECTION_ARCS)
        {
            if (*p=='-')
            {
                if (graph->nb_arcs>=YG_MAX_ARCS) { yg_set_error(graph,line_no,"too many arcs"); fclose(f); return YG_ERR_TOO_MANY_ARCS; }
                current_arc=&graph->arcs[graph->nb_arcs];
                if (!yg_start_arc(current_arc,p)) { yg_set_error(graph,line_no,"invalid arc declaration"); fclose(f); return YG_ERR_SYNTAX; }
                ++graph->nb_arcs;
            }
            else
            {
                if (current_arc==NULL) { yg_set_error(graph,line_no,"arc property before arc declaration"); fclose(f); return YG_ERR_SYNTAX; }
                if (!yg_parse_arc_property(current_arc,p)) { yg_set_error(graph,line_no,"invalid arc property"); fclose(f); return YG_ERR_SYNTAX; }
            }
        }
        else if (section==YG_SECTION_FORMATS)
        {
            if (*p=='-')
            {
                if (strcmp(p,"- format:")!=0) { yg_set_error(graph,line_no,"invalid format declaration"); fclose(f); return YG_ERR_SYNTAX; }
                if (graph->nb_formats>=YG_MAX_FORMATS) { yg_set_error(graph,line_no,"too many formats"); fclose(f); return YG_ERR_TOO_MANY_FORMATS; }
                current_format=&graph->formats[graph->nb_formats];
                yg_init_format(current_format);
                ++graph->nb_formats;
                current_format_field[0]='\0';
            }
            else
            {
                if (current_format==NULL) { yg_set_error(graph,line_no,"format property before format declaration"); fclose(f); return YG_ERR_SYNTAX; }
                if (!yg_key_value(p,key,(int)sizeof(key),&value)) { yg_set_error(graph,line_no,"invalid format property"); fclose(f); return YG_ERR_SYNTAX; }
                if (ind==6)
                {
                    if (strcmp(key,"formatID")==0)
                    {
                        if (!yg_parse_int(value,&current_format->format_id)) { yg_set_error(graph,line_no,"invalid formatID"); fclose(f); return YG_ERR_SYNTAX; }
                        current_format_field[0]='\0';
                    }
                    else if ((strcmp(key,"data_type")==0) || (strcmp(key,"sample_rate")==0) ||
                             (strcmp(key,"nb_channels")==0) || (strcmp(key,"interleaving")==0))
                    {
                        yg_copy_trimmed(current_format_field,(int)sizeof(current_format_field),key);
                    }
                    else current_format_field[0]='\0';
                }
                else if ((ind>=8) && (strcmp(key,"default")==0))
                {
                    if (strcmp(current_format_field,"data_type")==0)
                    { yg_copy_text_value(current_format->data_type,(int)sizeof(current_format->data_type),value); current_format->present|=YG_FORMAT_HAS_DATA_TYPE; }
                    else if (strcmp(current_format_field,"sample_rate")==0)
                    { if(!yg_parse_double(value,&current_format->sample_rate)) { yg_set_error(graph,line_no,"invalid format sample_rate"); fclose(f); return YG_ERR_SYNTAX; } current_format->present|=YG_FORMAT_HAS_SAMPLE_RATE; }
                    else if (strcmp(current_format_field,"nb_channels")==0)
                    { if(!yg_parse_int(value,&current_format->nb_channels)) { yg_set_error(graph,line_no,"invalid format nb_channels"); fclose(f); return YG_ERR_SYNTAX; } current_format->present|=YG_FORMAT_HAS_NB_CHANNELS; }
                    else if (strcmp(current_format_field,"interleaving")==0)
                    { yg_copy_text_value(current_format->interleaving,(int)sizeof(current_format->interleaving),value); current_format->present|=YG_FORMAT_HAS_INTERLEAVING; }
                }
                /* type: and values: are schema metadata. The graph compiler needs
                 * the selected/default value, so they are deliberately accepted
                 * without duplicating the allowed-value tables in RAM. */
            }
        }
        else
        {
            yg_set_error(graph,line_no,"content found outside nodes/arcs/formats section"); fclose(f); return YG_ERR_SYNTAX;
        }
    }
    fclose(f);
    n=0;
    while (n<graph->nb_arcs)
    {
        if ((graph->arcs[n].source.port<0) || (graph->arcs[n].destination.port<0))
        { yg_set_error(graph,0,"arc has a missing endpoint"); return YG_ERR_SYNTAX; }
        ++n;
    }
    return YG_OK;
}

const YG_Node *yg_find_node(const YG_Graph *graph, const char *base_name, int instance_index)
{
    int i;
    if ((graph==NULL)||(base_name==NULL)) return NULL;
    i=0;
    while (i<graph->nb_nodes)
    {
        if ((graph->nodes[i].instance_index==instance_index) && (strcmp(graph->nodes[i].base_name,base_name)==0)) return &graph->nodes[i];
        ++i;
    }
    return NULL;
}

const YG_Node *yg_find_full_node_name(const YG_Graph *graph, const char *name)
{
    int i;
    if ((graph==NULL)||(name==NULL)) return NULL;
    i=0;
    while (i<graph->nb_nodes)
    {
        if (strcmp(graph->nodes[i].name,name)==0) return &graph->nodes[i];
        ++i;
    }
    return NULL;
}

const YG_NamedParameter *yg_find_node_parameter(const YG_Node *node, const char *name)
{
    int i;
    if ((node==NULL)||(name==NULL)) return NULL;
    i=0;
    while (i<node->nb_named_parameters)
    {
        if (strcmp(node->named_parameter[i].name,name)==0) return &node->named_parameter[i];
        ++i;
    }
    return NULL;
}

const YG_Format *yg_find_format(const YG_Graph *graph, int format_id)
{
    int i;
    if (graph==NULL) return NULL;
    i=0;
    while (i<graph->nb_formats)
    {
        if (graph->formats[i].format_id==format_id) return &graph->formats[i];
        ++i;
    }
    return NULL;
}

#ifdef YAML_GRAPH_TEST
static const char *yg_test_kind(YG_ItemKind kind)
{
    return (kind == YG_ITEM_IO) ? "IO" : "node";
}

int main(int argc, char **argv)
{
    YG_Graph g;
    const char *filename;
    int rc;
    int i;
    int j;

    filename = (argc > 1) ? argv[1] : "graph.txt";
    rc = yg_read_file(filename, &g);
    if (rc != YG_OK)
    {
        fprintf(stderr, "parse error %d, line %d: %s\n", rc, g.error_line, g.error_text);
        return 1;
    }

    printf("graph.present=0x%lx\n", g.present);
    printf("platform=%s\n", g.platform);
    printf("nodes=%d\n", g.nb_nodes);
    for (i = 0; i < g.nb_nodes; ++i)
    {
        const YG_Node *n = &g.nodes[i];
        printf("  node[%d].present=0x%lx kind=%s name=%s local_name=%s base_name=%s instance_index=%d scope=%s hierarchy_depth=%d\n",
               i, n->present, yg_test_kind(n->kind), n->name, n->local_name, n->base_name,
               n->instance_index, n->scope, n->hierarchy_depth);
        printf("    framel=%d period=%g per_hr=%g per_day=%g domain=%s nbchan=%d samprt=%g samprt_percent_accuracy=%g\n",
               n->framel, n->period, n->per_hr, n->per_day, n->domain, n->nbchan,
               n->samprt, n->samprt_percent_accuracy);
        printf("    unit=%s scale=%g data_type=%s time_stamp=%s interleaving=%s\n",
               n->unit, n->scale, n->data_type, n->time_stamp, n->interleaving);
        printf("    nb_params=%d", n->nb_params);
        for (j = 0; j < n->nb_params; ++j) printf(" params[%d]=%g", j, n->params[j]);
        printf("\n");
        printf("    paramtxt=%s paramFile=%s preset=%d minopp=%d script=%s formatID=%s\n",
               n->paramtxt, n->param_file, n->preset, n->minopp, n->script, n->format_id);
        printf("    named_parameters=%d\n", n->nb_named_parameters);
        for (j = 0; j < n->nb_named_parameters; ++j)
            printf("      parameter[%d] name=%s value=%s\n", j,
                   n->named_parameter[j].name, n->named_parameter[j].value);
    }

    printf("arcs=%d\n", g.nb_arcs);
    for (i = 0; i < g.nb_arcs; ++i)
    {
        const YG_Arc *a = &g.arcs[i];
        printf("  arc[%d].present=0x%lx\n", i, a->present);
        printf("    source: port=%d kind=%s name=%s local_name=%s base_name=%s instance_index=%d scope=%s hierarchy_depth=%d\n",
               a->source.port, yg_test_kind(a->source.kind), a->source.name,
               a->source.local_name, a->source.base_name, a->source.instance_index,
               a->source.scope, a->source.hierarchy_depth);
        printf("    destination: port=%d kind=%s name=%s local_name=%s base_name=%s instance_index=%d scope=%s hierarchy_depth=%d\n",
               a->destination.port, yg_test_kind(a->destination.kind), a->destination.name,
               a->destination.local_name, a->destination.base_name, a->destination.instance_index,
               a->destination.scope, a->destination.hierarchy_depth);
        printf("    arc_name=%s buffer_size=%d data_type=%s sample_rate=%g nb_channels=%d interleaving=%s\n",
               a->arc_name, a->buffer_size, a->data_type, a->sample_rate,
               a->nb_channels, a->interleaving);
        printf("    refresh=%s jitter_percent=%g overlay_with=%s formatID=%s script=%s\n",
               a->refresh, a->jitter_percent, a->overlay_with, a->format_id, a->script);
    }

    printf("formats=%d\n", g.nb_formats);
    for (i = 0; i < g.nb_formats; ++i)
    {
        const YG_Format *f = &g.formats[i];
        printf("  format[%d].present=0x%lx formatID=%d data_type=%s sample_rate=%g nb_channels=%d interleaving=%s\n",
               i, f->present, f->format_id, f->data_type, f->sample_rate,
               f->nb_channels, f->interleaving);
    }
    printf("error_line=%d error_text=%s\n\n\n\n\n", g.error_line, g.error_text);
    return 0;
}
#endif
