#ifndef YAML_GRAPH_H
#define YAML_GRAPH_H

/*
 * yaml_graph.h
 *
 * Small, self-contained parser for the restricted YAML-like graph format
 * generated by the NanoGraph GUI.
 *
 * C90/C89 compatible, no heap allocation. This is intentionally NOT a
 * general YAML parser.
 */

#define YG_MAX_NODES             64
#define YG_MAX_ARCS             128
#define YG_MAX_FORMATS           64
#define YG_MAX_NAME             256
#define YG_MAX_LOCAL_NAME        64
#define YG_MAX_SCOPE            256
#define YG_MAX_PLATFORM          64
#define YG_MAX_DOMAIN            32
#define YG_MAX_DATA_TYPE         32
#define YG_MAX_TEXT             256
#define YG_MAX_SCRIPT           128
#define YG_MAX_REFRESH           32
#define YG_MAX_PARAMS            16
#define YG_MAX_NAMED_PARAMS      32
#define YG_MAX_PARAM_NAME        64
#define YG_MAX_PARAM_VALUE      128
#define YG_MAX_UNIT              32
#define YG_MAX_TIMESTAMP         32
#define YG_MAX_INTERLEAVING      32
#define YG_MAX_FORMAT_ID         64
#define YG_MAX_LINE             512

#define YG_OK                       0
#define YG_ERR_OPEN                -1
#define YG_ERR_TOO_MANY_NODES      -2
#define YG_ERR_TOO_MANY_ARCS       -3
#define YG_ERR_SYNTAX              -4
#define YG_ERR_LINE_TOO_LONG       -5
#define YG_ERR_TOO_MANY_PARAMS     -6
#define YG_ERR_TOO_MANY_FORMATS    -7

typedef enum
{
    YG_ITEM_NODE = 0,
    YG_ITEM_IO   = 1
} YG_ItemKind;

typedef struct
{
    char name[YG_MAX_PARAM_NAME];
    char value[YG_MAX_PARAM_VALUE];
} YG_NamedParameter;

typedef struct
{
    YG_ItemKind kind;

    /* Full possibly mangled instance name. */
    char name[YG_MAX_NAME];

    /* Name local to the containing graph/subgraph and its base type. */
    char local_name[YG_MAX_LOCAL_NAME];
    char base_name[YG_MAX_LOCAL_NAME];
    int instance_index;

    /* Parent mangling scope and hierarchy depth. */
    char scope[YG_MAX_SCOPE];
    int hierarchy_depth;

    /* IO/common stream properties. */
    int framel;
    double period;
    double per_hr;
    double per_day;
    char domain[YG_MAX_DOMAIN];
    int nbchan;
    double samprt;
    double samprt_percent_accuracy;
    char unit[YG_MAX_UNIT];
    double scale;
    char data_type[YG_MAX_DATA_TYPE];
    char time_stamp[YG_MAX_TIMESTAMP];
    char interleaving[YG_MAX_INTERLEAVING];

    /* Parameter escape hatches.
     * paramtxt: inline free-form parameter text.
     * param_file: external parameter file path/name (YAML key: paramFile).
     * Legacy numeric params[] is retained only so old graph files remain readable. */
    int nb_params;
    double params[YG_MAX_PARAMS];
    char paramtxt[YG_MAX_TEXT];
    char param_file[YG_MAX_TEXT];

    /* Node scheduling/configuration properties. */
    int preset;
    int minopp;
    char script[YG_MAX_SCRIPT];
    char format_id[YG_MAX_FORMAT_ID];

    /* Manifest-driven named parameters exported under "parameters:". */
    int nb_named_parameters;
    YG_NamedParameter named_parameter[YG_MAX_NAMED_PARAMS];

    unsigned long present;
} YG_Node;

typedef struct
{
    int port;
    YG_ItemKind kind;

    char name[YG_MAX_NAME];
    char local_name[YG_MAX_LOCAL_NAME];
    char base_name[YG_MAX_LOCAL_NAME];
    int instance_index;
    char scope[YG_MAX_SCOPE];
    int hierarchy_depth;
} YG_Endpoint;

typedef struct
{
    int format_id;
    char data_type[YG_MAX_DATA_TYPE];
    double sample_rate;
    int nb_channels;
    char interleaving[YG_MAX_INTERLEAVING];
    unsigned long present;
} YG_Format;

#define YG_FORMAT_HAS_DATA_TYPE      0x0001UL
#define YG_FORMAT_HAS_SAMPLE_RATE    0x0002UL
#define YG_FORMAT_HAS_NB_CHANNELS    0x0004UL
#define YG_FORMAT_HAS_INTERLEAVING   0x0008UL

typedef struct
{
    YG_Endpoint source;
    YG_Endpoint destination;

    char arc_name[YG_MAX_NAME];
    int buffer_size;
    char data_type[YG_MAX_DATA_TYPE];
    double sample_rate;
    int nb_channels;
    char interleaving[YG_MAX_INTERLEAVING];
    char refresh[YG_MAX_REFRESH];
    double jitter_percent;
    char overlay_with[YG_MAX_NAME];
    char format_id[YG_MAX_FORMAT_ID];
    char script[YG_MAX_SCRIPT];

    unsigned long present;
} YG_Arc;

typedef struct
{
    char platform[YG_MAX_PLATFORM];
    unsigned long present;

    int nb_nodes;
    YG_Node nodes[YG_MAX_NODES];

    int nb_arcs;
    YG_Arc arcs[YG_MAX_ARCS];

    int nb_formats;
    YG_Format formats[YG_MAX_FORMATS];

    int error_line;
    char error_text[YG_MAX_TEXT];
} YG_Graph;

/* Graph presence bits. */
#define YG_GRAPH_HAS_PLATFORM          0x0001UL

/* Node presence bits. */
#define YG_NODE_HAS_FRAMEL             0x00000001UL
#define YG_NODE_HAS_PERIOD             0x00000002UL
#define YG_NODE_HAS_PER_HR             0x00000004UL
#define YG_NODE_HAS_PER_DAY            0x00000008UL
#define YG_NODE_HAS_DOMAIN             0x00000010UL
#define YG_NODE_HAS_NBCHAN             0x00000020UL
#define YG_NODE_HAS_SAMPRT             0x00000040UL
#define YG_NODE_HAS_SAMPRT_ACCURACY    0x00000080UL
#define YG_NODE_HAS_UNIT               0x00000100UL
#define YG_NODE_HAS_SCALE              0x00000200UL
#define YG_NODE_HAS_DATA_TYPE          0x00000400UL
#define YG_NODE_HAS_TIME_STAMP         0x00000800UL
#define YG_NODE_HAS_INTERLEAVING       0x00001000UL
#define YG_NODE_HAS_PARAMS             0x00002000UL
#define YG_NODE_HAS_PARAMTXT           0x00004000UL
#define YG_NODE_HAS_PRESET             0x00008000UL
#define YG_NODE_HAS_MINOPP             0x00010000UL
#define YG_NODE_HAS_SCRIPT             0x00020000UL
#define YG_NODE_HAS_NAMED_PARAMETERS   0x00040000UL
#define YG_NODE_HAS_FORMAT_ID          0x00080000UL
#define YG_NODE_HAS_PARAM_FILE         0x00100000UL

/* Arc presence bits. */
#define YG_ARC_HAS_NAME                0x0001UL
#define YG_ARC_HAS_BUFFER_SIZE         0x0002UL
#define YG_ARC_HAS_DATA_TYPE           0x0004UL
#define YG_ARC_HAS_REFRESH             0x0008UL
#define YG_ARC_HAS_JITTER              0x0010UL
#define YG_ARC_HAS_OVERLAY_WITH        0x0020UL
#define YG_ARC_HAS_SCRIPT              0x0040UL
#define YG_ARC_HAS_FORMAT_ID           0x0080UL
#define YG_ARC_HAS_SAMPLE_RATE         0x0100UL
#define YG_ARC_HAS_NB_CHANNELS         0x0200UL
#define YG_ARC_HAS_INTERLEAVING        0x0400UL

#ifdef __cplusplus
extern "C" {
#endif

int yg_read_file(const char *filename, YG_Graph *graph);

int yg_split_instance_name(const char *name,
                           char *base_name,
                           int base_name_size,
                           int *instance_index);


/* Split the logical platform-IO syntax "io_name[index]".
 * If no bracket suffix is present, instance_index is -1. */
int yg_split_io_name(const char *name,
                     char *base_name,
                     int base_name_size,
                     int *instance_index);

int yg_split_mangled_name(const char *name,
                          char *scope,
                          int scope_size,
                          char *local_name,
                          int local_name_size,
                          char *base_name,
                          int base_name_size,
                          int *instance_index,
                          int *hierarchy_depth);

const YG_Node *yg_find_node(const YG_Graph *graph,
                            const char *base_name,
                            int instance_index);
const YG_Node *yg_find_full_node_name(const YG_Graph *graph,
                                      const char *name);
const YG_NamedParameter *yg_find_node_parameter(const YG_Node *node,
                                                 const char *name);

const YG_Format *yg_find_format(const YG_Graph *graph, int format_id);

#ifdef __cplusplus
}
#endif

#endif
