node: arm_script
node_designer : arm (ltd)
version: 1
description: data converter


interfaces:
  - rx_interface:               
    index: 0                                                
    name: input0        
    
    domain: general
    format:
      interleaving: 
        type: enum
        values: [interleaved, deinterleaved]
      data_type:
        default: int16              
        values:  [int8,int16,int32,int64,  uint8,uint16,uint32,uint64,  float32,float64,  utf8,utf16]
      frame_length:
        type: int
      sample_rate:
        type: float
      nb_channels:
        type: int

  - tx_interface:   # often connected to dummy SINK ports to allocate a buffer (arc_size)
    index: 0                                                
    name: output0        
    
    domain: general
    format:
      interleaving: 
        type: enum
        values: [interleaved, deinterleaved]
      data_type:
        default: int16              
        values:  [int8,int16,int32,int64,  uint8,uint16,uint32,uint64,  float32,float64,  utf8,utf16]
      frame_length:
        type: int
      sample_rate:
        type: float
      nb_channels:
        type: int
      

parameters:
  - name: mode
    type: enum
    default: none
    values: [disabled, check_input, call_before_each_node, call_after_each_node, call_at_start_of_scheduling_loop, call_at_end_of_scheduling_loop, called_after_reset, called_on_stop]
    help: options of "main" script, called during graph scheduling


# assembly code is made for a specific familty of processors
implementation:
  header: arm_script.h
  init: arm_script_init   # name of the entry point for CMSIS-STREAM
  process: arm_script_process # name of the entry point for CMSIS-STREAM / NanoGraphInterpreter
  malloc: precomputed     # precomputed / dynamic allocation without help of NanoGraph
  reentrant: no           # code is reentrant
  compatibility: 101      # the node is tested with framework V.101 and before
  nb_memory_banks: 1      # number of memory banks

  memoryBank2:
    - index: 0
      mem_alloc: 78       # (coef + state)50 + (pointers + index)24
      mem_type: static    # static / working / periodic_backup / pseudo_working 
      mem_speed: normal   # critical / fast / normal / coprocessor memory


