node: eml_tjpgdec
node_designer : EML
version: 1
description: 

interfaces:
  - rx_interface:               
    index: 0                                                 
    name: input0        
    
    domain: general
    format:
      
      data_type:
        default: uint8              
        values: [uint8]

      frame_length:
        type: int

      sample_rate:
        type: float

      nb_channels:
        type: int
        default: 1
        values: [1] 

  - tx_interface:                     
    index: 0                                                 
    name: output0        
    
    domain: 2d_out
    format:
     
      data_type:
        default: uint8              
        values: [uint8]

      frame_length:
        type: int

      sample_rate:
        type: float

      nb_channels:
        type: int
        default: 1
        values: [1]
      

parameters:
  - name: mode
    type: enum
    default: highquality
    values: [lowpower, intermediate, highquality]
    help: decoding quality

activation:
  key: 8234758358235    



# assembly code is made for a specific familty of processors
implementation:
  language: C90           # plain old C 
  complexity: 10e3        # 10kCycles average per call
  header: arm_filter.h
  init: arm_filter_init       # name of the entry point for CMSIS-STREAM
  process: arm_filter_process # name of the entry point for CMSIS-STREAM / NanoGraphInterpreter
  processor_architecture: armv7m, armv8m # list of processor architectures
  processor_fpu_option: double  # double precision FPU
  malloc: precomputed       # precomputed / dynamic allocation without help of NanoGraph
  reentrant: yes            # code is reentrant
  compatibility: 101        # the node is tested with framework V.101 and before
  nb_memory_banks: 2        # number of memory banks

  # memsize = 
  # A + 							   (fixed memory allocation in Bytes)
  # B x frame_size(mono) of arc(i) or max(input/output arcs) or their sum +
  # C x frame_size(mono) x nb_channel of arc(j) + 
  # D x nb_channels of arc(k) 
  #    + parameter from the graph optional field "node_malloc_add"
  memoryBank1:
    - index: 0
      mreloc: 1             # command 'STREAM_UPDATE_RELOCATABLE' is used with address changes
      mclear: 1             # the scheduler clears the memory at reset time
      mmdata0prog1: 0       # data / program access
      mtype: static         # 
      malloc_a: 24          # 24 bytes for the instance (2xint32 + 2xptr64)
      malloc_b: 12          # "B"
      malloc_b_type: 0      # take the max/min/sum of all input/output arcs/frame sizes
      malloc_b_arc: 0       # index of arc(i) in the above equation
      malloc_c: 12          # "C"
      malloc_c_arc: 0       # "j" in the formula
      malloc_d: 12          # "D"
      malloc_d_arc: 0       # "k" in the formula
      mspeed: fast          # critical / fast / best-effort / coprocessor memory
        
  memoryBank2:      
    - index: 1      
      malloc_a: 78          # (coef + state)50 + (pointers + index)24
      mtype: working        # static / working / periodic_backup / pseudo_working 
      mspeed: critical      # critical / fast / best-effort / coprocessor memory
      format: format1
  library: 16               # dependency to DSP services
