#ifndef YAML_GRAPH_H
#define YAML_GRAPH_H

/*
 * yaml_graph.h
 *
 * Small, self-contained parser for the restricted YAML-like graph format
 * generated by the GUI.
 *
 * Written to C90/C89 language rules:
 *   - no // comments
 *   - no declarations inside for-loop initializers
 *   - no C99 designated initializers
 *   - no variable length arrays
 *
 * This is intentionally NOT a general YAML parser.
 */

#define YG_MAX_NODES        64
#define YG_MAX_ARCS         128
#define YG_MAX_NAME         64
#define YG_MAX_DOMAIN       32
#define YG_MAX_DATA_TYPE    32
#define YG_MAX_TEXT         256
#define YG_MAX_SCRIPT       128
#define YG_MAX_REFRESH      32
#define YG_MAX_PARAMS       16
#define YG_MAX_LINE         512

/* Return values. */
#define YG_OK                0
#define YG_ERR_OPEN         -1
#define YG_ERR_TOO_MANY_NODES -2
#define YG_ERR_TOO_MANY_ARCS  -3
#define YG_ERR_SYNTAX       -4
#define YG_ERR_LINE_TOO_LONG -5

typedef enum
{
    YG_ITEM_NODE = 0,
    YG_ITEM_IO   = 1
} YG_ItemKind;

typedef struct
{
    YG_ItemKind kind;

    /*
     * Full instance name as found in the file.
     * Example: "arm_router_12"
     */
    char name[YG_MAX_NAME];

    /*
     * Name with a final "_<decimal number>" removed.
     * Example: "arm_router"
     *
     * If no final instance suffix exists, base_name == name and
     * instance_index == -1.
     */
    char base_name[YG_MAX_NAME];
    int instance_index;

    int framel;
    char domain[YG_MAX_DOMAIN];
    int nbchan;
    double samprt;
    char data_type[YG_MAX_DATA_TYPE];

    int preset;
    int nb_params;
    double params[YG_MAX_PARAMS];

    /*
     * Stored as text. UTF-8 bytes are preserved unchanged.
     */
    char paramtxt[YG_MAX_TEXT];

    int maxopp;
    char script[YG_MAX_SCRIPT];

    /*
     * Presence flags are useful because zero may be a legitimate value.
     */
    unsigned long present;
} YG_Node;

typedef struct
{
    int port;
    YG_ItemKind kind;

    /* Full endpoint name, e.g. "arm_router_12". */
    char name[YG_MAX_NAME];

    /* Parsed instance information, e.g. "arm_router", 12. */
    char base_name[YG_MAX_NAME];
    int instance_index;
} YG_Endpoint;

typedef struct
{
    YG_Endpoint source;
    YG_Endpoint destination;

    char arc_name[YG_MAX_NAME];
    int buffer_size;
    char data_type[YG_MAX_DATA_TYPE];
    char refresh[YG_MAX_REFRESH];
    double jitter_percent;
    char script[YG_MAX_SCRIPT];

    unsigned long present;
} YG_Arc;

typedef struct
{
    int nb_nodes;
    YG_Node nodes[YG_MAX_NODES];

    int nb_arcs;
    YG_Arc arcs[YG_MAX_ARCS];

    /*
     * Filled on syntax errors when possible.
     */
    int error_line;
    char error_text[YG_MAX_TEXT];
} YG_Graph;

/* Node presence bits. */
#define YG_NODE_HAS_FRAMEL      0x0001UL
#define YG_NODE_HAS_DOMAIN      0x0002UL
#define YG_NODE_HAS_NBCHAN      0x0004UL
#define YG_NODE_HAS_SAMPRT      0x0008UL
#define YG_NODE_HAS_DATA_TYPE   0x0010UL
#define YG_NODE_HAS_PRESET      0x0020UL
#define YG_NODE_HAS_PARAMS      0x0040UL
#define YG_NODE_HAS_PARAMTXT    0x0080UL
#define YG_NODE_HAS_MAXOPP      0x0100UL
#define YG_NODE_HAS_SCRIPT      0x0200UL

/* Arc presence bits. */
#define YG_ARC_HAS_NAME          0x0001UL
#define YG_ARC_HAS_BUFFER_SIZE   0x0002UL
#define YG_ARC_HAS_DATA_TYPE     0x0004UL
#define YG_ARC_HAS_REFRESH       0x0008UL
#define YG_ARC_HAS_JITTER        0x0010UL
#define YG_ARC_HAS_SCRIPT        0x0020UL

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Read a graph file.
 *
 * Returns YG_OK on success, otherwise one of YG_ERR_*.
 */
int yg_read_file(const char *filename, YG_Graph *graph);

/*
 * Split a final "_<decimal integer>" suffix.
 *
 * Examples:
 *   "arm_router_12" -> base_name="arm_router", instance_index=12
 *   "filter_0"      -> base_name="filter",     instance_index=0
 *   "filter"        -> base_name="filter",     instance_index=-1
 *
 * Returns 1 if a suffix was found, 0 otherwise.
 */
int yg_split_instance_name(const char *name,
                           char *base_name,
                           int base_name_size,
                           int *instance_index);

/*
 * Convenience lookup helpers.
 * Return NULL if no matching object is found.
 */
const YG_Node *yg_find_node(const YG_Graph *graph,
                            const char *base_name,
                            int instance_index);

const YG_Node *yg_find_full_node_name(const YG_Graph *graph,
                                      const char *name);

#ifdef __cplusplus
}
#endif

#endif
