#ifndef YAML_GRAPH_H
#define YAML_GRAPH_H

/*
 * yaml_graph.h
 *
 * Small, self-contained parser for the restricted YAML-like graph format
 * generated by the GUI.
 *
 * Written to C90/C89 language rules:
 *   - no // comments
 *   - no declarations inside for-loop initializers
 *   - no C99 designated initializers
 *   - no variable length arrays
 *
 * This is intentionally NOT a general YAML parser.
 */

#define YG_MAX_NODES        64
#define YG_MAX_ARCS         128
#define YG_MAX_NAME         128
#define YG_MAX_LOCAL_NAME   64
#define YG_MAX_SCOPE        128
#define YG_MAX_DOMAIN       32
#define YG_MAX_DATA_TYPE    32
#define YG_MAX_TEXT         256
#define YG_MAX_SCRIPT       128
#define YG_MAX_REFRESH      32
#define YG_MAX_PARAMS       16
#define YG_MAX_LINE         512

 /* Return values. */
#define YG_OK                0
#define YG_ERR_OPEN         -1
#define YG_ERR_TOO_MANY_NODES -2
#define YG_ERR_TOO_MANY_ARCS  -3
#define YG_ERR_SYNTAX       -4
#define YG_ERR_LINE_TOO_LONG -5

typedef enum
{
    YG_ITEM_NODE = 0,
    YG_ITEM_IO = 1
} YG_ItemKind;

typedef struct
{
    YG_ItemKind kind;

    /*
     * Full (possibly mangled) instance name as found in the file.
     * Example: "arm_filter_cascade_0__arm_filter_1"
     */
    char name[YG_MAX_NAME];

    /*
     * Name local to the containing graph/subgraph.
     * Example: "arm_filter_1"
     */
    char local_name[YG_MAX_LOCAL_NAME];

    /*
     * Local node type with the final "_<decimal number>" removed.
     * Example: "arm_filter"
     */
    char base_name[YG_MAX_LOCAL_NAME];
    int instance_index;

    /*
     * Mangled parent scope. Empty for a top-level node.
     * Example: "arm_filter_cascade_0"
     * Nested example:
     * "front_end_0__arm_filter_cascade_1"
     */
    char scope[YG_MAX_SCOPE];

    /* Number of "__" hierarchy separators in name. */
    int hierarchy_depth;

    int framel;
    char domain[YG_MAX_DOMAIN];
    int nbchan;
    double samprt;
    char data_type[YG_MAX_DATA_TYPE];

    int preset;
    int nb_params;
    double params[YG_MAX_PARAMS];

    /*
     * Stored as text. UTF-8 bytes are preserved unchanged.
     */
    char paramtxt[YG_MAX_TEXT];

    int maxopp;
    char script[YG_MAX_SCRIPT];

    /*
     * Presence flags are useful because zero may be a legitimate value.
     */
    unsigned long present;
} YG_Node;

typedef struct
{
    int port;
    YG_ItemKind kind;

    /* Full possibly mangled endpoint name. */
    char name[YG_MAX_NAME];

    /* Local name and parsed local instance information. */
    char local_name[YG_MAX_LOCAL_NAME];
    char base_name[YG_MAX_LOCAL_NAME];
    int instance_index;

    /* Parent mangling scope and nesting depth. */
    char scope[YG_MAX_SCOPE];
    int hierarchy_depth;
} YG_Endpoint;

typedef struct
{
    YG_Endpoint source;
    YG_Endpoint destination;

    char arc_name[YG_MAX_NAME];
    int buffer_size;
    char data_type[YG_MAX_DATA_TYPE];
    char refresh[YG_MAX_REFRESH];
    double jitter_percent;
    char script[YG_MAX_SCRIPT];

    unsigned long present;
} YG_Arc;

typedef struct
{
    int nb_nodes;
    YG_Node nodes[YG_MAX_NODES];

    int nb_arcs;
    YG_Arc arcs[YG_MAX_ARCS];

    /*
     * Filled on syntax errors when possible.
     */
    int error_line;
    char error_text[YG_MAX_TEXT];
} YG_Graph;

/* Node presence bits. */
#define YG_NODE_HAS_FRAMEL      0x0001UL
#define YG_NODE_HAS_DOMAIN      0x0002UL
#define YG_NODE_HAS_NBCHAN      0x0004UL
#define YG_NODE_HAS_SAMPRT      0x0008UL
#define YG_NODE_HAS_DATA_TYPE   0x0010UL
#define YG_NODE_HAS_PRESET      0x0020UL
#define YG_NODE_HAS_PARAMS      0x0040UL
#define YG_NODE_HAS_PARAMTXT    0x0080UL
#define YG_NODE_HAS_MAXOPP      0x0100UL
#define YG_NODE_HAS_SCRIPT      0x0200UL

/* Arc presence bits. */
#define YG_ARC_HAS_NAME          0x0001UL
#define YG_ARC_HAS_BUFFER_SIZE   0x0002UL
#define YG_ARC_HAS_DATA_TYPE     0x0004UL
#define YG_ARC_HAS_REFRESH       0x0008UL
#define YG_ARC_HAS_JITTER        0x0010UL
#define YG_ARC_HAS_SCRIPT        0x0020UL

#ifdef __cplusplus
extern "C" {
#endif

    /*
     * Read a graph file.
     *
     * Returns YG_OK on success, otherwise one of YG_ERR_*.
     */
    int yg_read_file(const char* filename, YG_Graph* graph);

    /*
     * Split a final "_<decimal integer>" suffix.
     *
     * Examples:
     *   "arm_router_12" -> base_name="arm_router", instance_index=12
     *   "filter_0"      -> base_name="filter",     instance_index=0
     *   "filter"        -> base_name="filter",     instance_index=-1
     *
     * Returns 1 if a suffix was found, 0 otherwise.
     */
    int yg_split_instance_name(const char* name,
        char* base_name,
        int base_name_size,
        int* instance_index);


    /*
     * Split a mangled graph name.
     *
     * Example:
     *   "arm_filter_cascade_0__arm_filter_1"
     *      scope          = "arm_filter_cascade_0"
     *      local_name     = "arm_filter_1"
     *      base_name      = "arm_filter"
     *      instance_index = 1
     *      hierarchy_depth= 1
     *
     * For a top-level name such as "arm_filter_0", scope is empty and
     * hierarchy_depth is zero.
     */
    int yg_split_mangled_name(const char* name,
        char* scope,
        int scope_size,
        char* local_name,
        int local_name_size,
        char* base_name,
        int base_name_size,
        int* instance_index,
        int* hierarchy_depth);

    /*
     * Convenience lookup helpers.
     * Return NULL if no matching object is found.
     */
    const YG_Node* yg_find_node(const YG_Graph* graph,
        const char* base_name,
        int instance_index);

    const YG_Node* yg_find_node_in_scope(const YG_Graph* graph,
        const char* scope,
        const char* base_name,
        int instance_index);

    const YG_Node* yg_find_full_node_name(const YG_Graph* graph,
        const char* name);

#ifdef __cplusplus
}
#endif

#endif
